allergydb/allergydb/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('recipe/', include('bclookup.urls')),
    path('admin/', admin.site.urls),
    path('allergyshop/', include('allergyshop.urls')),

]

allergydb/allergyshop/urls.py
from django.conf.urls import url
from .import views
from django.urls import path

urlpatterns = [
        # url(r'', views.listproducts, name='list_of_products'),
        # url(r'^(?P<category_slug>[-\w]+)/$', views.listproducts,
        # http://localhost:8000/allergyshop/
        path('', views.index, name='index'),
        path('product/<int:product_id>/', views.product_detail, name='product_detail'),
        path('product/<int:product_id>/comment/', views.product_comment, name='product_comment'),
]

allergydb/bclookup/urls.py
from django.urls import path

from . import views

app_name = 'bclookup'
urlpatterns = [
    path('enter/', views.barcode_entry, name='bcenter'),
    path('lookup/', views.barcode_lookup, name='bclookup'),
]

allergydb/allergyshop/models.py
from django.db import models

# Create your models here.

class Allergen(models.Model):
    name = models.CharField(max_length=1000, db_index=True)
    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)

class Store(models.Model):
    name = models.CharField(max_length=250, db_index=True)
    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)

class Category(models.Model):
    name = models.CharField(max_length=250, db_index=True)
     
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
                
    def __str__(self):
        return self.name

class Barcode(models.Model):
    code = models.CharField(max_length=250, db_index=True)

    def __str__(self):
        return self.code

    class Meta:
        ordering = ('code',)

class Product(models.Model):
    name = models.CharField(max_length=250, db_index=True)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    # allergens = models.ManyToManyField(Allergen)
    allergens = models.CharField(max_length=250, db_index=True, default=None)
    stores = models.CharField(max_length=250, db_index=True, default=None)
    barcode = models.CharField(max_length=250, db_index=True, default=None)
    picture = models.CharField(max_length=250, db_index=True, default=None)
    ingredients = models.TextField()

    def __str__(self):
        return self.name

    def get_stores(self):
        if self.stores:
            return self.stores.split(' ')
        return []

    def get_allergens(self):
        if self.allergens:
            return [f'image/{allergen}.jpg' for allergen in self.allergens.split(' ') if allergen != 'Nil'][:6:]
        return []

    class Meta:
        ordering = ('name',)

class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    comment_text = models.TextField()
    username = models.CharField(max_length=250)
    pub_date = models.DateTimeField()
    approved = models.BooleanField(default=False)

    def __str__(self):
        return self.comment_text
       

    
        

allergydb/bclookup/models.py
from django.db import models

# Create your models here.

allergydb/allergydb/views.py
from django.shortcuts import render_to_response

def home(request):
    context= {}
    return render_to_response('home.html', context=context)

allergydb/allergyshop/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from .models import Category, Allergen, Store, Product
from django.shortcuts import render_to_response

from django.db.models import Q

from django.utils import timezone


def listproducts(request, category_slug=None):
    category =  None
    categories = Category.objects.all()
    if category_slug:
        category = get_object_or_404(Category)
        products = Product.filter(category=category)
    return render(request, 'allergyshop/product/list.html', {'category': category, 'categories':categories, 'products': products})

def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'allergyshop/detail.html', {'product':product})

def product_comment(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    product.comment_set.create(comment_text=request.POST['comment'], username=request.POST['username'], pub_date=timezone.now())
    return HttpResponseRedirect(reverse('product_detail', args=(product.id,)))

def index(request):

    products = Product.objects.all()

    results = ""

    if 'barcode_search' in request.GET:
        search = request.GET.get('barcode_search')
        if search != "":
            results = Product.objects.filter(barcode__icontains=search)
        else:
            results = ""

    if 'search' in request.GET:  # If the form is submitted
        item_name = request.GET.get('item_search')
        item_category = request.GET.get('category')
        item_allergens = request.GET.get('allergens')
        print("name: ", item_name, " category: ", item_category, "allergens: ", item_allergens)
        allergen_list = item_allergens.split(",") if item_allergens else []

        results = Product.objects.all()
        for allergen in allergen_list:
            results = results.filter(~Q(allergens__icontains=allergen))
            #print(#"aaaa")
            #print(len(results))

        if item_category != "":
            if len(results) != 0:
                #print("ccc")
                results = results.filter(category__name__icontains=item_category)
                #print("results: ", results)
        if item_name and len(results) != 0:
            #print("ddd")
            results = results.filter(name__icontains=item_name)

    return render_to_response('allergyshop/index.html', {'results': results, 'products': products})

allergydb/bclookup/views.py
from django.shortcuts import render
from .food_api import get_recipes

def barcode_entry(request):
    return render(request, 'bclookup/entry.html')

def barcode_lookup(request):
    search = request.POST['search']
    allergies = request.POST['allergies']
    food_info = get_recipes(search, allergies)
    return render(request, 'bclookup/view.html', {'food_info': food_info})

allergydb/allergyshop/templates/allergyshop/detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>The Allergen Filter</title>
    <!--<link href="css/bootstrap.min.css" rel="stylesheet">-->
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}">
    <!-- <link href="css/index-style.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="{% static 'detail-style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
    <script src="{% static 'jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-inverse navbar-static-top">
      	<div class="container">
      		<div class="navbar-header">
            <div class="navbar-brand">
            <div class="logo">
              <div class="inner-logo">
                <a href="/allergyshop" class="af">AF<a href="">
              </div>
            </div>
      			<a href="/allergyshop" >The Allergen Filter</a>
          </div>
      		</div>
      	</div>
      </nav>
    </header>
    <main>
      <div class="container">
    		<div class="product-detail col-md-12">
    		  <h3>{{ product.name }}</h3>
    		  <div class="form-row">
			  <i>{{ product.category.name }}</i>
			  </div>
			  <div class="form-row">
              <img src="{{ product.picture }}" height="300px">
			  </div>
              
				<div class="form-row" style="padding:10px;">
				{% for allergen in product.get_allergens %}
				<img src="{% static allergen %}" height="35px">
				{% endfor %}
				</div>
    		  <h4>Available in</h4>
    		  <ul style="list-style-type: none;">
				{% for store in product.get_stores %}
				<li><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&emsp;<a href="#">{{ store }}</a></li>
				{% endfor %}
    		  </ul>
			  <h4>Ingredients</h4>
    		  <ul>
				<li>{{ product.ingredients }}</li>

    		  </ul>
    		</div>

            <div class="col-md-12">
            <h4>Comments</h4>
            <div class="col-md-12 comments-section">
            {% for comment in product.comment_set.all %}
        		<div class="col-md-12 comment-box">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                    <h6 class="username" style="display:inline;">{{ comment.username }}</h6>
        		    <p>{{ comment.comment_text }}</p>
        		</div>
    		{% endfor %}
            </div>
        </div>

        <form class="col-md-12" action="{% url 'product_comment' product.id %}" method="post">
          <h4>Add a comment</h4>
          {% csrf_token %}
          <div class="add-comment">
            <h5><label for="username">Username</label></h5>
            <input type="text" name="username" class="form-control">
            <h5><label for="comment">Comment</label></h5>
            <textarea rows="4" cols="50" name="comment" class="form-control"></textarea>
            <input type="submit" value="Comment" class="btn btn-default">
          </div>
        </form>

    </div>
    </div>

      <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->
      <!--<script src="js/bootstrap.min.js"></script>-->
    </main>
    <footer>
      - Made in 24 hours for UniHack Sydney 2018 -
    </footer>
  </body>
</html>

allergydb/allergyshop/templates/allergyshop/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>The Allergen Filter</title>
    <!--<link href="css/bootstrap.min.css" rel="stylesheet">-->
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}">
    <!-- <link href="css/index-style.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="{% static 'index-style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">

    <script src="{% static 'jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-inverse navbar-static-top">
      	<div class="container">
      		<div class="navbar-header">
            <div class="navbar-brand">
            <div class="logo">
              <div class="inner-logo">
                <a href="" class="af">AF</a>
              </div>
            </div>
      			<a href="#" >The Allergen Filter</a>
          </div>
      		</div>
      	</div>
      </nav>
    </header>
    <main>
    <div class="container">
        <div class="para">
      <p>The Allergen Filter provides a valuable database for searching and retrieving information about foods and potential allergens contained in their ingredients.
      To begin, enter the product name or barcode along with any allergens that you have. Then click search.</p>
        </div>
    </div>
      <div class = "container search-cat">

        <!--Barcode search-->
        <div class= "row">
          <form action="." method="GET">
            <div class="col-md-2 col-sm-2">
            <h4>Barcode:</h4>
          </div>
          <div class="col-md-3 col-sm-4">
            <div class = "input-group">
              <input name="barcode_search" type = "text" class = "barcode-search form-control" placeholder = "Barcode">
            </div>
          </div>
          <div class="col-md-2 col-sm-2">
            <button class = "bs btn btn-default" type="submit">Search</button>
          </div>
          </form>
        </div>

        <div class = "row">
          <h4 class="col-md-12">or</h4>
        </div>

        <!--Advanced Search-->
        <form action="." method="GET">
          <div class = "row">
              <div class="col-md-2 col-sm-3">
                <h4>Product name:</h4>
              </div>
              <div class="col-md-3 col-sm-3">
                <div class = "input-group">
                  <input name="item_search" type = "text" class = "form-control" placeholder = "Search product...">
                </div>
              </div>
              <div class="col-md-1 col-sm-3">
                <h4>Category:</h4>
              </div>
              <div class="col-md-3 col-sm-3">
                <select name="category" class="form-control">
                  <option value="">Select one...</option>
                  <option value="fruit">Fruit</option>
                  <option value="vegetable">Vegetable</option>
                  <option value="meat">Meat</option>
                  <option value="seafood">Seafood</option>
                  <option value="deli">Deli</option>
                  <option value="bakery">Bakery</option>
                  <option value="dairy">Dairy</option>
                  <option value="eggs">Eggs</option>
                  <option value="fridge">Fridge</option>
                  <option value="pantry">Pantry</option>
                  <option value="freezer">Freezer</option>
                  <option value="drinks">Drinks</option>
                </select>
              </div>
              <div class="col-md-3">
              </div>
            </div>
            <div class="row">
              <div class="col-md-1 col-sm-2">
                <h4>Allergen:</h4>
              </div>
              <div class="col-md-8 col-sm-10" style="padding-top: 5px;">
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
                <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
                <input name="allergens" type="text" list="allergens" id="authors" value="" placeholder="Allergens" class="form-control">
                <datalist id="allergens">
                  <option value="Gluten">
                  <option value="Crustacean">
                  <option value="Eggs">
                  <option value="Fish">
                  <option value="Peanuts">
                  <option value="Soybean">
                  <option value="Milk">
                  <option value="Nuts">
                  <option value="Celery">
                  <option value="Mustard">
                  <option value="Sesame">
                  <option value="Lupin">
                  <option value="Molluscs">
                </datalist>
                <script>
                  var datalist = jQuery('datalist');
                  var options = jQuery('datalist option');
                  var optionsarray = jQuery.map(options ,function(option) {
                        return option.value;
                  });
                  var input = jQuery('input[list]');
                  var inputcommas = (input.val().match(/,/g)||[]).length;
                  var separator = ',';

                  function filldatalist(prefix) {
                    if (input.val().indexOf(separator) > -1 && options.length > 0) {
                        datalist.empty();
                        for (i=0; i < optionsarray.length; i++ ) {
                            if (prefix.indexOf(optionsarray[i]) < 0 ) {
                                datalist.append('<option value="'+prefix+optionsarray[i]+'">');
                            }
                        }
                    }
                  }
                  input.bind("change paste keyup",function() {
                    var inputtrim = input.val().replace(/^\s+|\s+$/g, "");
                    //console.log(inputtrim);
                    var currentcommas = (input.val().match(/,/g)||[]).length;
                    //console.log(currentcommas);
                    if (inputtrim != input.val()) {
                        if (inputcommas != currentcommas) {
                            var lsIndex = inputtrim.lastIndexOf(separator);
                            var str = (lsIndex != -1) ? inputtrim.substr(0, lsIndex)+", " : "";
                            filldatalist(str);
                            inputcommas = currentcommas;
                        }
                        input.val(inputtrim);
                    }
                  });
                </script>
              </div>
              <div class="col-md-2 col-sm-12">
                <button type="submit" class = "btn btn-default" name="search" value="search">Search</button>
              </div>
          </div>
        </form>


      <!--Search Results-->
      <div class="container search-results" id = "res">
      {% if results.count == 0 %}
        <h3>No Results Found</h3>
      {% else %}
        <h3>Search Results:</h3>
        <ul class="result-items">
		{% for result in results %}
			<li class="col-md-3 col-sm-6 col-xs-12">
            <div class="col-md-12">
              <h3>{{ result.name }}</h3>
			  <div class="form-row">
			  <i>{{ result.category.name }}</i>
			  </div>
			  <div class="form-row">
              <a href="{% url 'product_detail' result.id %}"><img src="{{ result.picture }}" height="100px"></a>
			  </div>

				<div class="form-row" style="padding:10px;">
				{% for allergen in result.get_allergens %}
				<img src="{% static allergen %}" height="35px">
				{% endfor %}
				</div>
            </div>
          </li>
		{% endfor %}
        </ul>
      {%  endif %}
      </div>
      <script>
        if (window.location.href.indexOf("?") > -1) {
          //document.write("I'm here");
          document.getElementById('res').style = "display: block";
        } else {
          //document.write("I'm not  here");
          document.getElementById('res').style = "display: none";
        }
      </script>
      <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->
      <!--<script src="js/bootstrap.min.js"></script>-->
    </main>
  </body>
  <!-- <script>
    function unselect() {
      for (var i=0; i<13; i++){
        document.getElementById("allergen"+i).checked = false;
      }
    }
  </script>-->
  <footer>
    - Made in 24 hours for UniHack Sydney 2018 -
  </footer>
</html>

allergydb/bclookup/templates/bclookup/entry.html
<h1>Enter search term and allergies</h1>

<form action="{% url 'bclookup:bclookup' %}" method="post">
{% csrf_token %}
<input type="text" name="search">
<input type="text" name="allergies">
<input type="submit" value="Lookup">
</form>

allergydb/bclookup/templates/bclookup/view.html
<ul>
{% for recipe in food_info.hits %}
	<li>{{ recipe.recipe.label }}</li>
{% endfor %}
</ul>

allergydb/templates/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'home.css' %}">
</head>
<body>
    <h3 class="home_content">Welcome to our Website!</h3>
</body>
</html>